server:
  port: 80
  servlet:
    context-path: /

#注册中心配置
dubbo:
  application:
    name: 005-p2p-web
  registry:
    address: zookeeper://10.0.200.100:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1