server:
  port: 8003

spring:
  #数据库链接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.200.100:3306/p2p
    username: root
    password: Cgsl@123
  #Redis配置信息
  redis:
    host: 10.0.200.100
    port: 6379
    password: Cgsl@123

#注册中心配置
dubbo:
  application:
    name: 003-p2p-dataservice
    logger: slf4j
  registry:
    address: zookeeper://10.0.200.100:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: -1